events:
  BlockBreakEvent:
    enabled: true
    type: "BLOCK"
    blocks:
      - "GROWN_WHEAT"
      - "SUGAR_CANE"
      - "GROWN_PUMPKIN"
      - "GROWN_CARROT"
      - "GROWN_POTATO"
      - "GROWN_MELON"
      - "CACTUS"
  BlockPlaceEvent:
    enabled: false
    type: "BLOCK"
    blocks: []
  EntityDeathEvent:
    enabled: true
    type: "ENTITY"
    entities: []
  CraftItemEvent:
    enabled: true
    type: "CRAFT"
    entities:
      - "FURNACE"