events:
  BlockBreakEvent:
    type: "BLOCK"
    blocks:
      - "GROWN_WHEAT"
      - "GOLD_ORE"
      - "IRON_ORE"
      - "GRASS_BLOCK"
      - "STONE"
    enabled: true
    actions:
      - "broadcast %player% broke a %block%!"
  BlockPlaceEvent:
    type: "BLOCK"
    blocks:
      - "DIAMOND_ORE"
      - "GOLD_ORE"
      - "IRON_ORE"
      - "GRASS_BLOCK"
      - "STONE"
    enabled: true
    actions:
      - "broadcast %player% placed a %block%!"
  EntityDeathEvent:
    type: "ENTITY"
    entities:
      - "COW"
      - "PIG"
      - "SHEEP"
      - "CHICKEN"
      - "ZOMBIE"
    enabled: true
    actions:
      - "broadcast %player% killed a %entity%!"
  CraftItemEvent:
    type: "CRAFT"
    entities:
      - "FURNACE"
    enabled: true
    actions:
      - "broadcast %player% crafted a %item%!"